name: testovoe
description: "A new Flutter project."
 
publish_to: 'none' 
 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-260.0.dev <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.6
  injectable: ^2.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed: ^2.4.6
  freezed_annotation: ^2.3.0
  json_annotation: ^4.8.1
  mask_text_input_formatter: ^2.8.0
  pinput: ^3.0.1
  flutter_hooks: ^0.20.4
  flutter_secure_storage: ^9.0.0
  realm: ^1.7.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/icons/
 